package es.iesnervion.diana.nowroom.Tools;

import java.util.ArrayList;

import es.iesnervion.diana.nowroom.Models.Usuario;


public class ListaUsuarios {

//    ArrayList<Usuario> usuarios;

    //método para añadir más usuarios
    public ArrayList<Usuario> addNuevoUsuario(String nombreUsuario, int edadUsuario) {
        ArrayList<Usuario> usuarios = getListaUsuarios();

        usuarios.add(new Usuario(nombreUsuario, edadUsuario));
        return usuarios;
    }


    public ArrayList<Usuario> getListaUsuarios() {
        ArrayList<Usuario> usuarios = new ArrayList<>();
        usuarios.add(new Usuario("Diana", 26));
        usuarios.add(new Usuario("Julio", 40));
        usuarios.add(new Usuario("Thelma", 23));
        usuarios.add(new Usuario("Alba", 10));
        usuarios.add(new Usuario("Juan", 20));
        usuarios.add(new Usuario("Álvaro", 45));
        usuarios.add(new Usuario("Luis", 24));
        usuarios.add(new Usuario("Bea", 30));
        usuarios.add(new Usuario("Diana", 26));
        usuarios.add(new Usuario("Julio", 40));
        usuarios.add(new Usuario("Thelma", 23));
        usuarios.add(new Usuario("Alba", 10));
        usuarios.add(new Usuario("Juan", 20));
        usuarios.add(new Usuario("Álvaro", 45));
        usuarios.add(new Usuario("Luis", 24));
        usuarios.add(new Usuario("Bea", 30));
        usuarios.add(new Usuario("Diana", 26));
        usuarios.add(new Usuario("Julio", 40));
        usuarios.add(new Usuario("Thelma", 23));
        usuarios.add(new Usuario("Alba", 10));
        usuarios.add(new Usuario("Juan", 20));
        usuarios.add(new Usuario("Álvaro", 45));
        usuarios.add(new Usuario("Luis", 24));
        usuarios.add(new Usuario("Bea", 30));
        usuarios.add(new Usuario("Diana", 26));
        usuarios.add(new Usuario("Julio", 40));
        usuarios.add(new Usuario("Thelma", 23));
        usuarios.add(new Usuario("Alba", 10));
        usuarios.add(new Usuario("Juan", 20));
        usuarios.add(new Usuario("Álvaro", 45));
        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));
//        usuarios.add(new Usuario("Diana", 26));
//        usuarios.add(new Usuario("Julio", 40));
//        usuarios.add(new Usuario("Thelma", 23));
//        usuarios.add(new Usuario("Alba", 10));
//        usuarios.add(new Usuario("Juan", 20));
//        usuarios.add(new Usuario("Álvaro", 45));
//        usuarios.add(new Usuario("Luis", 24));
//        usuarios.add(new Usuario("Bea", 30));

        return usuarios;
    }
}
